### ISSUE TITLE
Set full_message

### ISSUE THREAD

**Issue by flamein** [keeprocking/pygelf#10]
maybe describe on the README how to set full_message? if it's possible.
or make it possible if it's not?

**Comment by keeprocking** [comment]
What exactly do you expect to see in this field? Logging message is being sent in the "short_message" field, the "full_message" is used to keep stack trace in case of logging an exception, e.g.

    try:
        1/0
    except Exception as e:
        logging.exception(e)

**Comment by flamein** [comment]
well, that way would be as I expected.
If that is how it works now, maybe put an example in the README?

we handled it with an extra field for _stderr by the way.

**Comment by keeprocking** [comment]
Here you are. :)

https://github.com/keeprocking/pygelf/blob/master/README.rst#message-structure

**Comment by flamein** [comment]
nice =) that will help a lot of people i think =)
