### ISSUE TITLE
cant connect with TLS

### ISSUE THREAD

**Issue by ekimia** [keeprocking/pygelf#11]
as a test, im not including any certs and have validate to false without any luck. Switching to a TCP handler does work though. Correct me if im wrong, but wouldnt a TLS handler act the same as a TCP handler if validate is set to false?

**Comment by keeprocking** [comment]
It's probably because of ssl.wrap_socket call. Actually I don't know how does it act if no cert was provided, you can check it yourself in the code of 'ssl' module.

**Comment by jsargiot** [comment]
> Correct me if im wrong, but wouldnt a TLS handler act the same as a TCP handler if validate is set to false?

TLS encrypts the communication with the server, plain TCP doesn't, the `validate` merely instructs the handler to check the server certificate but the connection is still encrypted. If the server:port works with TCP you might need to check the server's configuration, usually there is an option to "Enable TLS"
