### ISSUE TITLE
Option to use LevelName instead of LevelNumber

### ISSUE THREAD

**Issue by ajpen** [keeprocking/pygelf#17]
I noticed the log level is logged as a number. but the README seems to promise the level name.

What do you think about an option to send the name instead of the level number? Its less ambiguous IMO.

**Comment by keeprocking** [comment]
That's not gonna work because GELF spec says that the "level" field type should be integer, see http://docs.graylog.org/en/stable/pages/gelf.html?highlight=level#gelf-format-specification for details.

**Comment by keeprocking** [comment]
PS: readme updated - https://github.com/keeprocking/pygelf#message-structure

**Comment by ajpen** [comment]
Great, thanks
