### ISSUE TITLE
Add support for using with a QueueHandler/QueueListener

### ISSUE THREAD

**Issue by thomascobb** [keeprocking/pygelf#19]
If Python3's QueueHandler/QueueListener are used then record.exc_info is
None, but record.exc_text contains the traceback. Reading the source of
the logging module it would appear that exc_text can safely be assumed
to contain the exception text if it is not None, so can be used to populate
graylog's full_message.

#18 contains an attempt to fix this

**Comment by keeprocking** [comment]
Thanks for this.
Released in 0.3.3.
