### ISSUE TITLE
TCP doesn't stream/no channel reuse?

### ISSUE THREAD

**Issue by jhaar** [keeprocking/pygelf#2]

**Comment by jhaar** [comment]
Hi there

I'm not sure I'm calling it correctly, but it looks like using TCP doesn't involve opening a TCP socket and then pumping all the GELF records through the same channel? ie it looks like it acts exactly like UDP - one packet - one record?

Am I doing it wrong? (probably ;-)

Thanks

**Comment by keeprocking** [comment]
I'm afraid I don't quite understand. Do you mean that the socket recreates on every log record? If so, it's not the case. The socket opens on the first call of SocketHandler's method 'send' and it doesn't close afterwards, so the socket doesn't open on every log record.

See line 505 of logging/handlers.py

    if self.sock is None:
        self.createSocket()

**Comment by jhaar** [comment]
OK - I was calling it incorrectly. I'm very new to python and haven't figured out the basics

I had a problem with wanting to load lines of data into a dictionary and was using 

 GelfTcpHandler(gelf_server, 12201,0,0, **gelfData)

..per line.

Now that I've thought about it, I've put that GelfTcpHandler outside the "while" loop and use "handle.additional_fields=gelfData" to load my additional fields in - and now I have one TCP channel with lots of data. Yay!

Sorry for wasting your time :-)
