### ISSUE TITLE
Add more flexibility for configuring additional fields

### ISSUE THREAD

**Issue by LingboTang** [keeprocking/pygelf#22]
Hi, I just started to use this package recently, and I found there's a possible change to make this package more flexible on configuration.

Currently I configured gelf handler in django `settings.py` like this:

```
handlers =  {
            'level': 'INFO',
            'class': 'pygelf.GelfUdpHandler',
            'host': GRAYLOG_ADDR,
            'port': GRAYLOG_PORT,
            '_extra': 'myExtra', 
            '_one_more': 'myOneMore'
        }
```

But I don't want my handlers to be a giant dictionary with a bunch of messed-up fields. So I want to pull these things out to an independent `extra_fields_dict` and pass it in handlers like blew:

```
extra_fields_dict = {
    '_extra': 'myExtra',
    '_one_more': 'myOneMore'
}
```

```
handlers =  {
            'level': 'INFO',
            'class': 'pygelf.GelfUdpHandler',
            'host': GRAYLOG_ADDR,
            'port': GRAYLOG_PORT,
            'additional_fields': extra_fields_dict
        }
```

I assume this will not be a difficult change, so I just wonder if you can add this flexibility to configuration.

**Comment by keeprocking** [comment]
Added support for the new `static_fields` parameter, see the small example below (both handlers are equal):
```
GelfTcpHandler(host='127.0.0.1', port=12201, **STATIC_FIELDS)
GelfTcpHandler(host='127.0.0.1', port=12201, static_fields=STATIC_FIELDS),
```
Released in `0.3.2`.
