### ISSUE TITLE
GelfTcpHandler/GelfUDPHandler not liked under CentOS-6

### ISSUE THREAD

**Issue by jhaar** [keeprocking/pygelf#3]
Hi there

I guess pygelf is written for python-2.7. Under python-2.6, those classes aren't liked - they generate the following error

Traceback (most recent call last):
  File "/usr/local/bin/filelogs-to-gelf2", line 76, in <module>
    handle = GelfTcpHandler(gelf_server, 12201,0,0)
  File "/usr/lib/python2.6/site-packages/pygelf/tcp.py", line 19, in __init__
    super(GelfTcpHandler, self).__init__(host, port)
TypeError: super() argument 1 must be type, not classobj

The fix is simple: it just needs to be defined as a "object". ie

class GelfTcpHandler(SocketHandler,object):

Apparently (this is what google told me) under python-2.7 "object" is the default,  whereas under 2.6 it has to be declared?

Anyway, making that change makes pygelf work on CentOS-6 (and any other python-2.6 system I guess)

**Comment by keeprocking** [comment]
Python 2.6 was released in 2008 and its official support ended in 2013. Can't you just update your python to 2.7?
There is a an issue with inheritance from 'object'. Base class for all logging handlers is Filterer. In python 2.6 it looks like

    class Filterer()

but in python 2.7+ it derives from 'object':

    class Filterer(object)

I don't know if everything will be ok in 2.7+ if I add additional deriving from 'object':

    Filterer(object) -> Handler(Filterer) -> SocketHandler(Handler) -> GelfTcpHandler(SocketHandler, object)

**Comment by jhaar** [comment]
CentOS-6/Redhat-6 is still "fully supported" by the vendors and a large chunk of the world is still running it. Yes I could manually install python-2.7, but then I might as well ditch using enterprise Linux OSes and move over to Arch or something else (as commercial vendors are *always* way behind current versions of *all* software). In my case it's all about installing pygelf on our Linux infrastructure (which I don't own or operate) in order to give those systems tools to push data into graylog - so I'm simply trying to make it work in our existing environment

I certainly understand your reluctance - I'll just include your (patched) package along with my script - so that it works for us on the older platform :-)
