### ISSUE TITLE
No error if server port is closed

### ISSUE THREAD

**Issue by cpandya2909** [keeprocking/pygelf#31]
I am using pygelf to send logs to graylog

this is my code

`self.gelfhandler = GelfTcpHandler(host=str(host), port=int(port),include_extra_fields=True)`

and then i am sending the log entry ( already converted to gelf)

`self.gelfhandler.send(json.dumps(message))`

but I am not getting any error if graylog port is not open or suddenly is closed inbetween.

**Comment by keeprocking** [comment]
pygelf does not override default SocketHandler's `send` method implementation, so I thing it's expected.
Also, why do you use `send` at all? Messages should be emitted using loggers, not handlers themselves.
