### ISSUE TITLE
source Field Value -- Feature Request

### ISSUE THREAD

**Issue by mitchya1** [keeprocking/pygelf#33]
It seems that `socket.getfqdn()` (`handlers.py`)  falls back to assigning the first FQDN it finds in `/etc/hosts`. So when a message comes into graylog, the source is localhost.localdomain (for people that haven't edited /etc/hosts manually). Making a call to `socket.gethostname()` returns the system's hostname as you'd expect to see it, so you know where the messages are _actually_ coming from. 

I'm happy to create a PR for the change.

 If it'd be a breaking change (I don't see how it would be), maybe a hint in the document would save some time and Googling.

Very cool tool, by the way! Saved me a ton of headaches:)

**Comment by keeprocking** [comment]
> I'm happy to create a PR for the change.

That would be nice of you, please do.

> Very cool tool, by the way! Saved me a ton of headaches:)

Glad to hear that. ;)

**Comment by mitchya1** [comment]
PR #34

**Comment by mitchya1** [comment]
Closing this as the change has been merged into master. Thank you!
