### ISSUE TITLE
Someone else has a pygelf app too...

### ISSUE THREAD

**Issue by jhaar** [keeprocking/pygelf#4]
Hi there

On the graylog website there's a link to pygelf - but it's not this pygelf!

https://marketplace.graylog.org/addons/77b60e7c-f041-4b2d-86d0-378884f387ec

It looks like someone else has a similar app - although it only supports HTTP

https://github.com/tgalyean/pygelf

Pistols at dawn perhaps? :-)

**Comment by keeprocking** [comment]
I've seen this library before. It was created before mine and it's quite different. The approach of my library is to provide logging interface that converts every log message into GELF. In fact https://github.com/tgalyean/pygelf is just a wrapper for pycurl. It has no integration with logging module.

Thanks for your attention to pygelf. :)

**Comment by keeprocking** [comment]
https://marketplace.graylog.org/addons/0dd10abe-18f7-4f53-9212-2ff432bbf7ef
I've added pygelf to the marketplace.

**Comment by keeprocking** [comment]
Also I wrote to graylog support on friday and asked them to add a link to pygelf here: https://www.graylog.org/resources/data-sources/
Still have no answer though.

**Comment by keeprocking** [comment]
Upd: https://www.graylog.org/resources/data-sources/ now leads to https://marketplace.graylog.org
