### ISSUE TITLE
KeyError when logging.BasicConfig initialized with object instead of int

### ISSUE THREAD

**Issue by vangourd** [keeprocking/pygelf#41]
Sorry newbie here. I get the following which seems like 

> --- Logging error ---                                                                                                                                                       Traceback (most recent call last):                                                                                                                                            File "/usr/lib/python3.6/logging/handlers.py", line 633, in emit                                                                                                              s = self.makePickle(record)                                                                                                                                               File "/usr/local/lib/python3.6/dist-packages/pygelf/handlers.py", line 58, in makePickle                                                                                      return self.convert_record_to_gelf(record) + b'\x00'                                                                                                                      File "/usr/local/lib/python3.6/dist-packages/pygelf/handlers.py", line 38, in convert_record_to_gelf                                                                          gelf.make(record, self.domain, self.debug, self.version, self.additional_fields, self.include_extra_fields),                                                              File "/usr/local/lib/python3.6/dist-packages/pygelf/gelf.py", line 37, in make                                                                                                'level': LEVELS[record.levelno],                                                                                                                                        KeyError: 5 

Which seems like this...

https://github.com/keeprocking/pygelf/blob/1483931f08b834ab8886abcc4cb477bf0b413452/pygelf/gelf.py#L10

"enumeration" type dict doesn't handle the event that a Level 5 is thrown. I don't know the specifics here but is this possibly a bug?

I would clone the repo and propose a PR but i'm still new to GH and would prefer to avoid the cognitive burden while I'm working on this task.

**Comment by keeprocking** [comment]
I might be missing something, but `logging.ERROR` is of type `int`: https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L93. What's the difference between passing an explicit integer (e.g. `40`) or `logging.ERROR` (which also stands for `40`)?

**Comment by vangourd** [comment]
Sorry been a while since I dug into this.

My recollection is that if logging.ERROR was passed INSTEAD of an Int you it would still try and match against the dict of values and throw a KeyError.

I'm not sure that it was Level 5 that caused the issue but that it was the object not the int.

Were you capable of recreating the error?

**Comment by keeprocking** [comment]
Unfortunately, not. That's why I asked about the difference.

If you could provide a small example to reproduce the error, it would be awesome.

**Comment by vangourd** [comment]
With `Python 3.7.1`
```
import logging
from pygelf import GelfUdpHandler

def setup(val):
    logging.basicConfig(level=val)
    logger = logging.getLogger()
    logger.addHandler(GelfUdpHandler(host='localhost',port=10118))
    logger.info("Hello World!")


if __name__ ==  "__main__":
    print("Result:" + str(setup(4) == setup(logging.ERROR)))
"""

Comes out showing identical results. 

Obviously something must have been wrong with my configuration. Sorry for the confusion.

**Comment by keeprocking** [comment]
No worries! Always happy to help.

Glad you got that sorted out.
