### ISSUE TITLE
Pass api key to seq

### ISSUE THREAD

**Issue by chr0m1ng** [keeprocking/pygelf#43]
I'm trying to use gelf to log to seq as shown in https://docs.datalust.co/docs/using-python 
But I couldn't find how to pass a api key in any documentation

**Comment by keeprocking** [comment]
Hi.

Personally I have no experience with seq but I'll try to help anyway.

From what I see from the docs, the API key is usually passed in the `X-Seq-ApiKey` HTTP header - but that obviously won't work for UDP.

So, either API keys are not supported for the UDP GELF handlers or there's another way to pass it to the server. I would recommend asking the fine folks from datalust directly as pygelf is just a logging library it knows nothing about seq.
