### ISSUE TITLE
every GELF record triggers getfqdn?

### ISSUE THREAD

**Issue by jhaar** [keeprocking/pygelf#8]
Hi there

I was debugging an unrelated issue and detected tonnes of DNS lookups for the hostname I was running pygelf on (permanent process, converting squid logs into GELF in realtime). It looks to me like pygelf is doing a DNS lookup for $HOSTNAME for every GELF record it generates? That's a nasty overhead if you're generating 100+/sec streams of GELF data

I don't know for sure, but could it be the "'source': socket.getfqdn()" in gelf.py that's doing that?

Shouldn't that be replaced by defining that as a variable at startup, and then just reusing that variable afterwards? I know the hostname could be put into /etc/hosts, but actually strace showed the DNS lookups occurring before /etc/hosts was opened - so I don't even think that would help - and even that's an overhead that could be skipped if it only did it once?

**Comment by keeprocking** [comment]
That's definitely a good idea, will implement soon.

**Comment by keeprocking** [comment]
Fixed in 0.2.6, already on pypi.

By the way, if I deprecate "source" field and replace it with "host" field, would it break something on your side? Currently domain name is sent in the "source" field but according to the latest spec this field should be named "host".

**Comment by jhaar** [comment]
Well that's weird - I'm a big user of graylog and all our incoming syslog data has 'source' set to the syslog client name. I see no evidence of that becoming "host"? ie incoming syslog data out of syslog agents looks like

timestamp syslogclient other

From what you are saying, wouldn't you expect that the latest version of graylog (v2.1.1) be setting "host=syslogclient" - I'm not seeing that. I'm not seeing any reference to a "host" field at all. (ie if graylog themselves aren't doing it for syslog, that's not much motivation to do it for GELF/pygelf)

BTW, I did a "pip install pygelf" and now I'm getting full_message:null - which wasn't happening on the older version of pygelf I had. I've always used short_message. How do I get rid of that, or couldn't you do something like require that either short_message or full_message be set, and remove the unused one? Just in case you don't know, graylog shows my short_message fields as "message", so now I have the situation that even though I'm setting "short_message", graylog is showing a "message" field and a "null" full_message field.

**Comment by keeprocking** [comment]
Sorry about that. Looks like it's related to the new field I added in the last commit.
As a temporary solution you can install previous version:

    pip install pygelf=0.2.5

**Comment by keeprocking** [comment]
Could you give me more info? The "full_message" field is used to store stack trace, the message itself is sent in the "short_message" field. Just tried it myself and everything works fine on graylog 2.1.1.

**Comment by keeprocking** [comment]
Oh, I guess I figured it out. The fix is on the way!

**Comment by keeprocking** [comment]
Fixed in 0.2.7.

Re source/host: looks like "host" overrides "source". Didn't find any docs regarding it.
