### ISSUE TITLE
support logger name as message field

### ISSUE THREAD

**Issue by s-trooper** [keeprocking/pygelf#9]
Hi, GELF says nothing about logger name but IMHO field you call "source" should be named "host" per "http://docs.graylog.org/en/2.1/pages/gelf.html" and "source" should be logger name. 

Anyway i think logger name should be added as additional field per default like other python handler handle it.

EDIT: btw i found this one "https://github.com/severb/graypy" and they write client host in "source" too =)

**Comment by keeprocking** [comment]
Thanks for pointing this out.
Looks like the naming was changed in GELF 2.0. Anyway, I started writing the "host" field in 0.2.6 and will deprecate the "source" field sometime in the future.

**Comment by keeprocking** [comment]
Looks like this new field broke something:
https://github.com/keeprocking/pygelf/issues/8#issuecomment-252512325
https://github.com/keeprocking/pygelf/issues/10

**Comment by keeprocking** [comment]
Actually it didn't but anyway - the docs say nothing about the "source" field. Perhaps it's still used for backward compatibility (tested on graylog 2.1.1) but the "host" field has higher priority, i.e. if the payload contains both of these fields, the "source" field will be ignored.

**Comment by keeprocking** [comment]
Personally I disagree with

> Anyway i think logger name should be added as additional field per default like other python handler handle it.

because it would increase the bandwidth usage. By default I try to keep everything as thin as possible. If one needs the logger name, he can easily add it to the config.

As an alternative, I can add this field under debug section, i.e. it will be automatically added to the record if logger is created with debug=True parameter:

    GelfTcpHandler(host='127.0.0.1', port=9401, debug=True)

**Comment by fooelisa** [comment]
Ran into this as well, some easy way to pass the logger name through would be great! 👍

**Comment by keeprocking** [comment]
Do you need it in every message on in debug ones only?

**Comment by fooelisa** [comment]
Either way would work for me, I have debug enabled, so that would do

**Comment by keeprocking** [comment]
Done in 0.2.11 for debug-enabled handlers only.

**Comment by fooelisa** [comment]
works like a charm!! thank you sir

**Comment by keeprocking** [comment]
My pleasure. :)
